Exception: Add QueueElementException and extension onNull to it
Very useful when you require nullable variable. Yes, you can use requireNotNull, but it will return non-custom Exception